[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft = "C3dsiPjuHb9YHPMe6RjJAFzXCFZtvLV3tFbUZycea1qz"

[programs.devnet]
mint_nft = "C3dsiPjuHb9YHPMe6RjJAFzXCFZtvLV3tFbUZycea1qz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
