[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft = "DxnbJwhqP2mZ7fwZipDjf4mwDETS13urV1D8dzVYWDbw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
