[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft = "Foe8RMYw3sAshTdTmG87rzbY7jsZdaWC9YmYF9k6ceXx"

[programs.devnet]
mint_nft = "Foe8RMYw3sAshTdTmG87rzbY7jsZdaWC9YmYF9k6ceXx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
